apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: game-session-hpa
spec:
  scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: game-session
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 50