extends Resource

export(String) var default = "Padrão"
export(String) var bandage = "Bandagem"
export(String) var militaries = "Militares"
export(String) var outlaws = "Foras da lei"
export(String) var renegades = "Renegados"
export(String) var ready = "Pronto"
export(String) var play = "Jogar"
export(String) var game_status = "Aguardando jogadores"
export(String) var game_title = "Zombie Waves"
export(String) var select_fac = "Selecione a facção"
export(String) var name = "Nome"
export(String) var health = "Saúde"
export(String) var prototype_pistol = "Prototipo de pistola"
export(String) var hold = "Segure"
export(String) var use = "Usar"
export(String) var equip = "Equipar"
export(String) var to_collect = "para coletar"
export(String) var hold_for = "Segure para"
export(String) var server_ip = "Ip do servidor"
export(String) var host_server = "Hospedar servidor"
export(String) var connect_server = "Conectar a um servidor"
export(String) var player_count_title = "Prontos  /  Conectados"
